config/routes.rb
MeasWeb::Application.routes.draw do
  resources :reports

  resources :report_templates

  resources :kinds

  resources :models do
    collection do
      get :autocomplete
      get :get_json      
    end  
  end

  resources :spreadsheets do
    collection do
      post :sort
      get :get_tendency
    end
  end

  resources :manufacturers
  resources :roles

  resources :assets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :snippets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :companies

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :sessions => "my_devise/sessions",
             :passwords => "my_devise/passwords"
           }
  resources :users do
    post 'invite', :on => :collection
    get 'manage'
    patch 'manage_update'
  end

  
  resources :services do
    resources :spreadsheets
  end

  resources :spreadsheets do
    collection do
      get :autocomplete
    end
  end

  resources :laboratories
  constraints(Subdomain) do  
    devise_scope :user do
      root to: "my_devise/sessions#new"
    end
  end    
  match '/' => "laboratories#new", via: [:get, :post, :put, :patch, :delete]

  mathjax 'mathjax'
  

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :reports, dependent: :destroy
	has_many :spreadsheets, dependent: :destroy
	#has_and_belongs_to_many :assets, join_table: :workbenches, primary_key: :id
	has_many :workbenches, -> { order "position"}, dependent: :destroy
	has_many :assets, :through => :workbenches
	belongs_to :user
	validates_presence_of :order_number
	default_scope { where(laboratory_id: Laboratory.current_id) }
	accepts_nested_attributes_for :assets, allow_destroy: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!
  before_action :role_required, only: [:create, :edit, :index]
  after_action :reorder, only: [:update, :create]
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def reorder
    # remove blank
    if not @service.new_record?
      assets = service_params[:asset_ids].reject! { |c| c.empty? }
      positions = params[:asset_positions]
      # Keep order if items
      assets.each_with_index do |asset, i|
        wb = @service.workbenches.where(:asset_id => asset).first
        wb.insert_at(positions[i].to_i(10))
      end
    end    
  end

  # GET /services
  # GET /services.json
  def index
    #@services = Service.all
    respond_to do |format|
      format.html
      format.json { render json: ServicesDatatable.new(view_context) }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @spreadsheets = @service.spreadsheets.order("position")
    @assets = @service.assets
    @reports = @service.reports
    @details_lines = @service.details.split("\n")
    respond_to do |format|
      format.html
      format.json { 
        render :json => {
          :laboratory => current_laboratory.as_json(),
          :service => @service.as_json(:include => :user),
          :spreadsheets => @spreadsheets,
          :assets => @assets.as_json(
            :include => 
            [
              :company,
              {
                :model => {
                  :only => :name, 
                  :include => 
                  [
                    {:kind => {:only => :name} },
                    {:manufacturer => {:only => :name} }
                  ]
                }
              }
            ]
          )
        }
      }
    end    
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    if cant_manage then
      access_denied
    else
      respond_to do |format|
        if @service.update(service_params)
          format.html { redirect_to service_path(@service, :tab => 'spreadsheets'), notice: 'Service was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @service.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    if cant_manage then
      access_denied
    else  
      @service.destroy
      respond_to do |format|
        format.html { redirect_to services_url }
        format.json { head :no_content }
      end
    end
  end

  private
    def cant_manage
      if (@service.validated and (not current_user.has_role?(:services, :update_validated))) or ((not @service.validated) and (not current_user.has_role?(:services, :update_unvalidated))) then
        return true
      else
        return false
      end
    end  
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:order_number, :details, :asset_id, :information, :user_id, :calibration_date, :validated, {:positions => []}, {:asset_ids => []})
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for @service do |f| %>

      <div id="teste">
        
      </div>


  <div class="service_assets_datatables_feature">
  <%= f.input :order_number, input_html: { class: 'form-control' } %>
  <%= f.input :details, input_html: { class: 'form-control'} %>
  <br>
  <%= f.input :validated, as: :boolean, boolean_style: :inline, label: false, input_html: { :data => {toggle: 'toggle', on: 'Validated', off: 'Unvalidated', onstyle: 'success'} } %>  
  <br>
  <div class="laboratory_id" data-lab-id="<%= current_user.laboratory_id %>"></div>
  <div class="information_holder"></div>
  <%= f.input :information, as: :text, label: false, input_html: { value: @service.information.to_json } %>
  <%= render "shared/modal_choose_value", f: f, :association => :user, :cols => [:name] , :value => (@service.user.nil? ? "Calibrated by..." : @service.user.name) %>
  <br>
  <%= render "shared/datepicker", f: f, :field => :calibration_date %><br>
  <%= raw_template :assets %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Click on the asset to put it on your workbench</h3>
    </div>
    <div class="panel-body">
      <%= render "shared/assets_datatable" %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Click over a workbench item below to enable replace it</h3>
        </div>
        <div class="panel-body">
          <div class="service_assets">
            <%= f.fields_for :assets do |builder| %>
              <%= render "shared/asset_fields", {:f => builder, :role => 'remove'} %>
            <% end %>
            <div class="assets-holder assets_holder_feature"></div>
            <%# 
            hidden field needed to allow remove all assets from the service 
            
            http://asciicasts.com/episodes/17-habtm-checkboxes 
            
            --One Small Gotcha
            There is still one small problem with our update method. If we uncheck all of the checkboxes to remove a product from all categories then the update fails to remove any categories the product was in. This is because a checkbox on an HTML form will not have its value sent back if it is unchecked and therefore no category_ids will appear in the product’s parameters hash, meaning that the category_ids are not updated.

            To fix this we have to modify our products controller to set the category_ids parameter to be an empty array if it is not passed to the update action. We can do this using Ruby’s ||= operator and add the following like at the top of the update action.            
            %>
            <input id="service_asset_ids_null" name="service[asset_ids][]" type="hidden">
          </div>
        </div>
      </div>
    </div>
  </div>
 
  <br>
  <%= f.button :submit, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                :back, :class => 'btn btn-default' %>
<% end %>

app/views/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/services/index.html.erb
<%- model_class = Service -%>

<div class="page-header">
  <%= link_to new_service_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New <%=t '.title', :default => model_class.model_name.human %>
  <% end %>
  <h1>Listing <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>


<table id="services" class="datatable table table-striped table-hover table-bordered service_datatables_feature" data-source="<%= services_url(format: "json") %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:order_number) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/services/new.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/services/show.html.erb
<%- model_class = Service -%>
<div class="panel panel-default">
<div class="panel-heading">
<input id="service_id_ref" type="hidden" value="<%= @service.id %>">
<strong><%= model_class.human_attribute_name(:order_number) %></strong>: <%= @service.order_number %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_service_path(@service), :class => 'btn btn-xs btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
      service_path(@service), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-danger btn-xs' %>
</div>
<div class="panel-body">
<ul class="nav nav-tabs">
  <li class="<%= 'active' if params[:tab] == 'spreadsheets'or (params[:tab] == nil)  %>"><a href="#spreadsheets" data-toggle="tab">Spreadsheets</a></li> 

  <li class="<%= 'active' if params[:tab] == 'reports' %>"><a href="#reports" data-toggle="tab">Reports</a></li> 
</ul>
<div class="tab-content">
  <div id="spreadsheets" class="tab-pane <%= 'active' if params[:tab] == 'spreadsheets' or (params[:tab] == nil) %>">
    <%- model_class = Spreadsheet -%>
    <br>
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <!-- <th><%= model_class.human_attribute_name(:description) %></th> -->
          <th>Tags</th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody id="spreadsheets_tbody" class="sortable_elements" data-update-url="<%= sort_spreadsheets_url %>">
        <% @spreadsheets.each do |spreadsheet| %>
          <tr data-id="<%= spreadsheet.id %>">
            <td class="my-handle"><span class="fa fa-arrows-v" aria-hidden="true"></span></td>
            <!-- <td><%= link_to spreadsheet.description.to_s, edit_spreadsheet_path(spreadsheet), :data => { :no_turbolink => true } %></td> -->
            <td><%= spreadsheet.tag_list %></td>
            <td><%= spreadsheet.created_at %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit") ),
                          edit_spreadsheet_path(spreadsheet), :class => 'btn btn-default btn-xs', :data => { :no_turbolink => true } %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          spreadsheet_path(spreadsheet),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to t('.new', :default => t("helpers.links.new") + " Spreadsheet"),
                new_spreadsheet_path(:service_id => @service),
                :class => 'btn btn-primary' %>
  </div>
  <div id="reports" class="tab-pane <%= 'active' if params[:tab] == 'reports' %>">



    <%- model_class = Report -%>
    <br>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th>Tags</th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td><%= link_to report.name.to_s, edit_report_path(report) %></td>
            <td><%= report.name %></td>
            <td><%= report.created_at %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_report_path(report), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          report_path(report),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to t('.new', :default => t("helpers.links.new") + " Report"),
                new_report_path(:service_id => @service),
                :class => 'btn btn-primary' %>


    <dl class="dl-horizontal">
      <div class='report_editor_feature' id='report_editor' style="margin-top: 30px;"></div>
    </dl>


  </div>
</div>  
<%#= link_to t('.back', :default => t("helpers.links.back")),
                  services_path, :class => 'btn btn-default'  %>
</div>
</div>