config/routes.rb
MeasWeb::Application.routes.draw do
  resources :reports

  resources :report_templates

  resources :kinds

  resources :models do
    collection do
      get :autocomplete
      get :get_json      
    end  
  end

  resources :spreadsheets do
    collection do
      post :sort
      get :get_tendency
    end
  end

  resources :manufacturers
  resources :roles

  resources :assets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :snippets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :companies

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :sessions => "my_devise/sessions",
             :passwords => "my_devise/passwords"
           }
  resources :users do
    post 'invite', :on => :collection
    get 'manage'
    patch 'manage_update'
  end

  
  resources :services do
    resources :spreadsheets
  end

  resources :spreadsheets do
    collection do
      get :autocomplete
    end
  end

  resources :laboratories
  constraints(Subdomain) do  
    devise_scope :user do
      root to: "my_devise/sessions#new"
    end
  end    
  match '/' => "laboratories#new", via: [:get, :post, :put, :patch, :delete]

  mathjax 'mathjax'
  

end

app/models/asset.rb
class Asset < ActiveRecord::Base
	acts_as_taggable
	belongs_to :laboratory
	belongs_to :company
	belongs_to :model
	#has_and_belongs_to_many :services, join_table: :workbenches
	has_many :workbenches, -> { order("position ASC") }
	has_many :services, :through => :workbenches
	default_scope { where(laboratory_id: Laboratory.current_id) }
	before_save :default_values

	def default_values
		self.reclassification ||= "{}"
	end

	attr_accessor :changeable
	attr_accessor :button_role
	attr_accessor :position
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
	has_many :assets
	belongs_to :laboratory
	default_scope { where(laboratory_id: Laboratory.current_id) }
end

app/models/kind.rb
class Kind < ActiveRecord::Base
	has_many :models
	default_scope { where(laboratory_id: Laboratory.current_id) }	
end

app/models/laboratory.rb
class Laboratory < ActiveRecord::Base
	has_many :users
	has_many :companies
	has_many :roles
	cattr_accessor :current_id
	extend DeviseOverrides
	validates_uniqueness_of :subdomain
	validates :name,
		presence: true,
		length: { :in => 3..30, message: 'Laboratory name must have 3 to 30 characters.' }
	validates :subdomain,
		presence: true,
		format: { with: /\A[a-z0-9]+\z/, :message => 'Subdomain must be lowercase.' },
		length: { :in => 2..15, :message => 'Subdomain must have 2 to 15 characters.' }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
	has_many :models
	default_scope { where(laboratory_id: Laboratory.current_id) }	
end

app/models/model.rb
class Model < ActiveRecord::Base
	acts_as_taggable
	acts_as_taggable_on :models
	belongs_to :kind
	belongs_to :manufacturer
	has_many :assets
	default_scope { where(laboratory_id: Laboratory.current_id) }	
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :service
	belongs_to :report_template
	default_scope { where(laboratory_id: Laboratory.current_id) }	
end

app/models/role.rb
class Role < ActiveRecord::Base
  include TheRole::Api::Role

  def _jsonable val
    val.is_a?(Hash) ? val : JSON.load(val)
  end

  def to_hash
    begin the_role rescue {} end
  end

  def to_json
    the_role.is_a?(Hash) ? the_role.to_json : the_role
  end
  
  default_scope { where(laboratory_id: Laboratory.current_id) }

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :reports, dependent: :destroy
	has_many :spreadsheets, dependent: :destroy
	#has_and_belongs_to_many :assets, join_table: :workbenches, primary_key: :id
	has_many :workbenches, -> { order "position"}, dependent: :destroy
	has_many :assets, :through => :workbenches
	belongs_to :user
	validates_presence_of :order_number
	default_scope { where(laboratory_id: Laboratory.current_id) }
	accepts_nested_attributes_for :assets, allow_destroy: true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
	acts_as_taggable
	acts_as_taggable_on :models, :functionalities
	default_scope { where(laboratory_id: Laboratory.current_id) }
end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
	acts_as_taggable
  belongs_to :service
	default_scope { where(laboratory_id: Laboratory.current_id) }
  #serialize :table_json, JSON
  #before_create do
  # self.table_json ||= {}
  #end  

end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_reader :raw_invitation_token
  attr_reader :reset_password_token, :reset_password_sent_at
  include TheRole::Api::User
  belongs_to :laboratory
  belongs_to :company
  has_many :services
  default_scope { where(laboratory_id: Laboratory.current_id) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Disabled :validatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :confirmable
  validates :email, 
    uniqueness: { scope: :laboratory_id, case_sensitive: false },
    presence: true
  validates :laboratory_id,
    presence: true
  validates :password,
    presence: true,
    length: { :in => 6..20 },
    :if => :password_required?
  validates_confirmation_of :email, :password,
                              message: 'should match.'
  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end  
  #class DeviseController < Devise.parent_controller.constantize
  #  set_current_laboratory_by_subdomain(:laboratory_id, :subdomain)
  #end
  #validates_uniqueness_of :email, scope: :laboratory_id
  #protected
    # copied from validatable module
end

app/models/workbench.rb
class Workbench < ActiveRecord::Base
	acts_as_list scope: :service
	belongs_to :asset
	belongs_to :service
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_asset_fields.erb
<fieldset obj-id="<%= params[:id] %>">

	<!-- Share template for new asset input using mustache -->
	<% template = '
	<span class="label label-primary {{changeable}}" style="font-size: small; cursor: default" data-model="{{model.manufacturer.name}} {{model.name}}">{{model.manufacturer.name}}, {{model.name}} {{model.kind.name}}</span>
	<span class="label label-default" style="font-size: small">{{identification}}</span>
	<span class="{{button_role}}_fields glyphicon glyphicon-{{button_role}}" style="cursor: pointer;"></span>
	<input class="form-control" id="service_asset_ids_{{id}}" name="service[asset_ids][]" type="hidden" value="{{id}}">
	<input class="position_map" id="asset_positions_{{id}}" asset_id="{{id}}" name="asset_positions[]" type="hidden" value="{{position}}">
	<br><br>
	'
	%>
	<!-- if its been rendered from fields_for (at page load), sent the rendered mustache templeta with the object -->
	<% if defined?(f) %>
		<% f.object.button_role = role %>
		<% f.object.changeable = "changeable" %>
		<%# Setting the position will keep the choosen assets on spreadsheets tied with the asset_service relation and keep possible to refresh data %>
		<% wb = f.object.workbenches.where(:service_id => @service.id).first %>
		<% wb_position = ( (wb == 'null') or wb.nil? ?  "" : wb.position) %>
		<% f.object.position = wb_position %>
		<%= raw ( Mustache.render(template, f.object) ) %>
		<%= hidden_field_tag(f.object.id, nil, data:{json: f.object.to_json}, class: 'asset_json_data', asset_id: f.object.id )%>
	<!-- Else, render the template. It will be used when the raw_template method is called, and the template will became avaliabpe to javascript 
	render json objects to new added items -->
	<% else %>
		<%= raw ( template ) %>
	<% end %>
</fieldset>

app/views/shared/_assets_datatable.erb
<%- model_class = Asset -%>
<table id="assets_datatable" class="datatable table table-striped table-hover table-bordered asset_datatables_feature" data-source="<%= assets_url(format: "json") %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:identification) %></th>
      <th><%= model_class.human_attribute_name(:serial) %></th>
      <th><%= model_class.human_attribute_name(:certificate) %></th>
      <th><%= model_class.human_attribute_name(:calibration_date) %></th>
      <th><%= model_class.human_attribute_name(:due_date) %></th>
      <th>Model</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/shared/_datepicker.erb
<%= f.label field %>
<div class="input-group date">
  <%= f.text_field field, :class => 'form-control', :value => f.object[field].nil? ? "" : f.object[field].strftime("%B %e, %Y") %>
  <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
</div>

app/views/shared/_modal_choose_value.erb
<fieldset class="value_chooser_feature">
  <%- association_str = association.to_s -%>

  <%= f.association association, as: :string, input_html: { class: 'value_reference hidden' } %>
  <div class="input-group" data-toggle="modal" data-target=".modal_<%=association_str%>" style="cursor: pointer">
    <span type="text" class="value_label form-control"><%= value %></span>
    <span class="glyphicon glyphicon-search input-group-addon" style="top: 0px;"></span>
  </div>


  <div class="modal modal_<%=association_str%> fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">Choose a <%= association.to_s %></h4>
        </div>
        <div class="modal-body">
          <%= render "shared/values_datatable", :klass => association_str.classify.constantize, :cols => cols %>
          <br>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>    
</fieldset>

app/views/shared/_snippets_datatable.erb
<%#= @locals.nil? ? "" : hidden_field_tag(@locals[:modifier], true) %>
<table id="snippets" class="datatable table table-striped table-hover table-bordered snippet_datatables_feature" data-source="<%= snippets_url(format: "json") %>">
  <thead>
    <tr>
      <th>Type</th>
      <th>Updated at</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/shared/_values_datatable.erb
<table class="datatable table table-striped table-hover table-bordered values_datatables_feature" data-klass="<%= klass %>" data-source="<%= url_for(klass) %>.json">
	<thead>
		<tr>
			<% cols.each do |col| %>
				<th class="values_datatables_header"><%= klass.human_attribute_name(col) %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>