config/routes.rb
MeasWeb::Application.routes.draw do
  resources :reports

  resources :report_templates

  resources :kinds

  resources :models do
    collection do
      get :autocomplete
      get :get_json      
    end  
  end

  resources :spreadsheets do
    collection do
      post :sort
      get :get_tendency
    end
  end

  resources :manufacturers
  resources :roles

  resources :assets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :snippets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :companies

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :sessions => "my_devise/sessions",
             :passwords => "my_devise/passwords"
           }
  resources :users do
    post 'invite', :on => :collection
    get 'manage'
    patch 'manage_update'
  end

  
  resources :services do
    resources :spreadsheets
  end

  resources :spreadsheets do
    collection do
      get :autocomplete
    end
  end

  resources :laboratories
  constraints(Subdomain) do  
    devise_scope :user do
      root to: "my_devise/sessions#new"
    end
  end    
  match '/' => "laboratories#new", via: [:get, :post, :put, :patch, :delete]

  mathjax 'mathjax'
  

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
	has_many :assets
	belongs_to :laboratory
	default_scope { where(laboratory_id: Laboratory.current_id) }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_action :role_required, only: [:update, :destroy, :create, :edit, :index]  
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    respond_to do |format|
      format.html
      format.json { render json: ValuesDatatable.new(view_context) }
    end        
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to edit_company_path(@company), notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to edit_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :address, :details)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company, :html => { :class => 'form-horizontal' } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: { class: 'form-control' } %>
    <%= f.input :address, input_html: { class: 'form-control' } %>
    <%= f.input :details, input_html: { class: 'form-control' } %>

  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="page-header">
  <%= link_to companies_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>

  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
      company_path(@company), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-danger' %>

  <h1>Editing company</h1>
</div>

<%= render 'form' %>

app/views/companies/index.html.erb
<%- model_class = Company -%>

<div class="page-header">
  <%= link_to new_company_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New <%=t '.title', :default => model_class.model_name.human %>
  <% end %>
  <h1>Listing <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>


<%= render "shared/values_datatable", :klass => model_class, :cols => [:name, :created_at] %>

app/views/companies/new.html.erb
<div class="page-header">
  <%= link_to companies_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New company</h1>
</div>

<%= render 'form' %>