config/routes.rb
MeasWeb::Application.routes.draw do
  resources :reports

  resources :report_templates

  resources :kinds

  resources :models do
    collection do
      get :autocomplete
      get :get_json      
    end  
  end

  resources :spreadsheets do
    collection do
      post :sort
      get :get_tendency
    end
  end

  resources :manufacturers
  resources :roles

  resources :assets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :snippets do
    collection do
      get :autocomplete
      get :get_json      
    end
  end

  resources :companies

  devise_for :users,
           :controllers  => {
             :registrations => 'my_devise/registrations',
             :sessions => "my_devise/sessions",
             :passwords => "my_devise/passwords"
           }
  resources :users do
    post 'invite', :on => :collection
    get 'manage'
    patch 'manage_update'
  end

  
  resources :services do
    resources :spreadsheets
  end

  resources :spreadsheets do
    collection do
      get :autocomplete
    end
  end

  resources :laboratories
  constraints(Subdomain) do  
    devise_scope :user do
      root to: "my_devise/sessions#new"
    end
  end    
  match '/' => "laboratories#new", via: [:get, :post, :put, :patch, :delete]

  mathjax 'mathjax'
  

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :service
	belongs_to :report_template
	default_scope { where(laboratory_id: Laboratory.current_id) }	
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :role_required, only: [:update, :destroy, :create, :edit, :index]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  #def index
  #  @reports = Report.all
  #end

  # GET /reports/1
  # GET /reports/1.json
  def show

    respond_to do |format|
      @laboratory = Laboratory.find(@report.laboratory_id)
      pdf_options = @report.pdf_options
      opts = {:pdf => "", :javascript_delay => "1000", :disable_smart_shrinking => false}.merge(pdf_options).deep_symbolize_keys

      format.html
      format.pdf do
          render(opts)
          #render :pdf => "show"
      end
    end
  end

  # GET /reports/new
  def new
    @service = Service.find(params[:service_id])
    @report = Report.new(service_id: @service.id)
    respond_to do |format|
      if @report.save
        format.html { redirect_to edit_report_path(@report.id), notice: 'Report was successfully created.' }
        format.json { render action: 'edit', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /reports/1/edit
  def edit
    @laboratory = Laboratory.find(@report.laboratory_id)
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    if cant_manage then
      access_denied
    else
      respond_to do |format|
        if @report.update(report_params)
          #format.html { redirect_to edit_report_path(@report), notice: 'Report was successfully updated.' }
          #format.json { head :no_content }
          format.js { render :js=>'console.log("saved!");' }
        else
          format.html { render action: 'edit' }
          format.json { render json: @report.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    if cant_manage then
      access_denied
    else    
      @report.destroy
      respond_to do |format|
        format.html { redirect_to service_url(@report.service, :tab => 'reports') }
        format.json { head :no_content }
      end
    end
  end

  private

    # This will be implemented on client side now
    #x = apply_template(nil, opts, @report.service.information)
    #def apply_template(parent, myHash, locals)
    #  myHash.each {|key, value|
    #    if value.is_a?(Hash) then
    #      apply_template(key, value, locals)
    #    else
    #      myHash[key] = Mustache.render(value, locals)
    #    end
    #  }
    #end

    def cant_manage
      @service = @report.service
      if (@service.validated and (not current_user.has_role?(:services, :update_validated))) or ((not @service.validated) and (not current_user.has_role?(:services, :update_unvalidated))) then
        return true
      else
        return false
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :value, :service_id, :laboratory_id, :report_template_id, :pdf_options, :value_html)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for @report, :remote => true, :html => { :class => 'report_feature' } do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name, input_html: { class: 'form-control' } %>
  </div>
  <%= f.hidden_field :service_id_ref, value: @report.service_id %>
  
  
	<%= render "shared/modal_choose_value", f: f, :association => :report_template, :cols => [:name, :created_at] , :value => (@report.report_template.nil? ? "Choose a report template..." : @report.report_template.name) %>
  <br>
  <a href="#" class="btn btn-primary generate">
    <span class="fa fa-file-text-o" aria-hidden="true"></span>
  Generate
  </a>

  <a href="#" class="btn btn-success getdata">
    <span class="fa fa-floppy-o" aria-hidden="true"></span>
  Save
  </a>

  <a href="#" class="btn btn-default getpdf">
    <span class="fa fa-file-pdf-o" aria-hidden="true"></span>
  PDF
  </a>
 
  <a href="#" class="btn btn-default printview">
    <span class="fa fa-print" aria-hidden="true"></span>
  Print view
  </a> 
  <!--
 <a href="#" class="btn btn-default markdownedit">
    <span class="fa fa-code" aria-hidden="true"></span>
  Markdown
  </a> 
  -->

  <hr>
<div id="lab_style">
  <%= raw @laboratory.custom_forms['styles'].html_safe %>
</div>

<iframe src="/clean-paste.html" id="editor_frame" frameborder="0" border="0" cellspacing="0"
        style="border-style: none;width: 1200px; height: 800px;">
</iframe>


<div id="f_editor"></div>




  <%= f.input :pdf_options, as: :hidden %>  
  <%= f.input :value, :label => false, input_html: { class: ' markdown_textarea', :rows => 20 } %>
  <%= f.input :value_html, :label => false, input_html: { class: 'report_editor_feature report_view' } %>
  <br>
<% end %>

app/views/reports/edit.html.erb
<%= mathjax_tag %>
<%- model_class = Report -%>
<%= link_to service_path(@report.service, :tab => 'reports'), :class => 'btn btn-default' do -%>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<%- end -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reports/index.html.erb
<div class="page-header">
  <%= link_to new_report_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Report
  <% end %>
  <h1>Listing reports</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Service</th>
            <th>Laboratory</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @reports) do |report| %>
            <td><%= report.name %></td>
            <td><%= report.value %></td>
            <td><%= report.service_id %></td>
            <td><%= report.laboratory_id %></td>
            <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reports/new.html.erb
<div class="page-header">
  <%= link_to reports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New report</h1>
</div>

<%= render 'form' %>

app/views/reports/show.html.erb
<%= render :partial => 'report' %>

app/views/reports/show.pdf.erb
<%= render :partial => 'report' %>